### ISSUE TITLE
Update workflow to latest rust version

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-rust#8]

**Comment by king-11** [comment]
Hi @Cliftonz can you please assign this to me I would like to work on it.

**Comment by Cliftonz** [comment]
@king-11 you are assigned!

**Comment by king-11** [comment]
A little unclear on this 😅  in the `testing.yml` we are running test against `nightly`, `stable` and `1.60`. By default `stable` points to latest rust stable version as of now `1.72.1`. we can get rid of the hardcoded value for most cases and set a `MSRV` (Minimum Supported Rust Version) instead.

**Comment by king-11** [comment]
@Cliftonz I have updated the rust version in `testing.yml` and `Cargo.toml` as well to match our Minimum Supported Version (MSRV) i.e. `1.63.0` found using tool [cargo-msrv](https://github.com/foresterre/cargo-msrv)
